# Generated by Django 3.1.3 on 2020-12-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
